ci: test

diff --git a/.github/workflows/test_ci.yml b/.github/workflows/test_ci.yml
--- a/.github/workflows/test_ci.yml
+++ b/.github/workflows/test_ci.yml
@@ -40,7 +40,21 @@ jobs:
             airflow variables set SLACK_KEY 'https://hooks.slack.com/services/dummy-webhook-url' &&
             airflow variables set LASTFM_API_KEY 'dummy'
           "
-      
+
+
+      - name: Check DAG import errors and fail if any
+        run: |
+          echo "📋 Checking DAG import errors..."
+          error_count=$(docker compose -f docker-compose_git.yml exec -T airflow-webserver airflow dags list-import-errors | grep -c "Traceback")
+
+          if [ "$error_count" -gt 0 ]; then
+            echo "Found $error_count DAG import error(s). Failing CI."
+            exit 1
+          else
+            echo "No DAG import errors found."
+          fi
+
+   
       - name: Test DAG parsing
         run: |
           echo "airflow dags list"
